### ISSUE TITLE
User-supplied scoring program

### ISSUE THREAD

**Issue by madclam** [CodalabOrg/chalab#19]
The specification give:
Version 2: The user will be able to supply his own scoring program.

Currently, users can select scoring programs from a menu. This is not sufficient to support many challenges that require specialized scoring programs and prevented some M2 student to use ChaLab. It should be possible to let them upload a function with the following syntax:

def scoring_metric(solution, prediction):
    return score

**Comment by CeVague** [comment]
Duplicate of #25
