### ISSUE TITLE
Uploading dataset

### ISSUE THREAD

**Issue by madclam** [CodalabOrg/chalab#2]
I keep getting errors when I upload dataset (server error 500). Since I get no feed-back, I cannot debug the problem. Here is a sample dataset:
[iris.zip](https://github.com/CodalabOrg/chalab/files/562071/iris.zip)

In general, the ingestion program for datasets needs to be more flexible:
- ingest any zip file without generating an error and lists its contents
- load the data and computes statistics about the dataset

We should support several formats, including the AutoML format and the RAMP and Kaggle format. Here is the dataset in RAMP format:

[Iris.csv.zip](https://github.com/CodalabOrg/chalab/files/562080/Iris.csv.zip)

By default, the last column has the target values.

**Comment by lsenta** [comment]
Validation issue on the input, fixed.
