### ISSUE TITLE
Error creating "digit" challenge

### ISSUE THREAD

**Issue by madclam** [CodalabOrg/chalab#21]
I tried creating a challenge with one of the default datasets (digits).
At build time, I got this error in the log file: https://chalab.lri.fr/wizard/challenges/6/bundler/logs

Create phase 2
        
            Exception: AttributeError("'NoneType' object has no attribute 'raw_content'",)
        
            Traceback:
Traceback (most recent call last):
  File "/app/bundler/tasks.py", line 188, in gen_final_phase
    task.target_test.raw_content.open()
AttributeError: 'NoneType' object has no attribute 'raw_content'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bundler/tasks.py", line 374, in bundle
    create_bundle(bundle_task, data, challenge)
  File "/app/bundler/tasks.py", line 254, in create_bundle
    phases = gen_phases(bt, output_dir, challenge)
  File "/app/bundler/tasks.py", line 208, in gen_phases
    challenge.protocol, challenge.metric)
  File "/app/bundler/tasks.py", line 198, in gen_final_phase
    task.target_test.raw_content.close()
AttributeError: 'NoneType' object has no attribute 'raw_content'

        
            Set state to failed

**Comment by CeVague** [comment]
It seems the solution of the test dataset is missing.
We have probably just to found it to correct this bug.

**Comment by CeVague** [comment]
So it was that : just one file missing in each dataset, but we can't distribute it here.
